### ISSUE TITLE
Small Insta feeds

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/David-Dodge--Internal--Jun-3#15]
The instafeeds are coming small in mobile & iPad
![image](https://user-images.githubusercontent.com/97726944/170991774-34166e28-1449-4a7a-adfb-8511fc10a574.png)

**Comment by ui-abrarul** [comment]
Since instagram images have too much whitespace, its size become automatically small in small sizes.

https://scontent.cdninstagram.com/v/t51.29350-15/284260456_351947910361645_4039715251474197580_n.webp?stp=dst-jpg&_nc_cat=111&ccb=1-7&_nc_sid=8ae9d6&_nc_ohc=wZno5ETFHBcAX9HWIDi&_nc_ht=scontent.cdninstagram.com&edm=ANo9K5cEAAAA&oh=00_AT8_-LedLpLJq2w_x1v2Va-ntI3NxGppyAVIl1syjupoQg&oe=629B6DC3
